GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6966a845123851d2c4064e6a

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "title": "nueva nota creada desde el backend",
    "description": "no está funcionando de momento:("
}

###
DELETE http://localhost:3001/api/notes/6966a5c3123851d2c4064e64

###
PUT http://localhost:3001/api/notes/6966a626123851d2c4064e66
Content-Type: application/json

{
    "title": "nota position 0 actualizada"
}
